server.port=8761

spring.application.name=eureka-server

# Eureka server ne registruje sam sebe u sopstveni registar
eureka.client.register-with-eureka=false
# ...niti povlaci kopiju registra sa drugog Eureka cvora (nemamo klaster)
eureka.client.fetch-registry=false
